// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace UmbracoBase.Web.Controllers.SurfaceControllers
{
    public partial class MetaController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MetaController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MetaTitle()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MetaTitle);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MetaController Actions { get { return MVC.Meta; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Meta";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Meta";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string MetaTitle = "MetaTitle";
            public readonly string MetaElements = "MetaElements";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string MetaTitle = "MetaTitle";
            public const string MetaElements = "MetaElements";
        }


        static readonly ActionParamsClass_MetaTitle s_params_MetaTitle = new ActionParamsClass_MetaTitle();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MetaTitle MetaTitleParams { get { return s_params_MetaTitle; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MetaTitle
        {
            public readonly string pageTitle = "pageTitle";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _MetaElements = "_MetaElements";
                public readonly string _MetaTitle = "_MetaTitle";
            }
            public readonly string _MetaElements = "~/Views/Meta/_MetaElements.cshtml";
            public readonly string _MetaTitle = "~/Views/Meta/_MetaTitle.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_MetaController : UmbracoBase.Web.Controllers.SurfaceControllers.MetaController
    {
        public T4MVC_MetaController() : base(Dummy.Instance) { }

        [NonAction]
        partial void MetaTitleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageTitle);

        [NonAction]
        public override System.Web.Mvc.ActionResult MetaTitle(string pageTitle)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MetaTitle);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageTitle", pageTitle);
            MetaTitleOverride(callInfo, pageTitle);
            return callInfo;
        }

        [NonAction]
        partial void MetaElementsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MetaElements()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MetaElements);
            MetaElementsOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
